# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a70b44d530163d45b11f92c8be2bd5aaa70a39cc2efcb294c8a494006f6587d8ebc35c8ce6c42e74376da903137a53f469ee50485209cd267479d5a1f2e63a1

test:
  secret_key_base: a076d194774da0fc51a2f34d4c3cece63fc0ea53ed7744c851488d73487fa86147ff25c838abb7014559489ca2c9d82f8e5aa8c95457feb910fc2efcbe545671

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
